#' Aligning sequences against references to produce annotation information
#'
#' Aligns sequences in a PAC list object against specified references, returning
#' a data frame or PAC object containing annotation information
#'
#' Given a PAC object, the destination of reference files, and information of
#' what type of information to save, this function will perform mapping against references
#' and retain information of mapping. This function is based of four main functions;
#'  \code{map_reanno}, \code{make_reanno}, \code{add_reanno}  and \code{simplify_reanno}, 
#'  which can be run separately for more detailed control of the workflow. 
#'  Using save_name=TRUE in this function will retain the name of the references where sequences are found,
#'  which may cause large objects.   
#'
#' @family PAC reannotation
#'
#' @seealso  \url{http://bowtie-bio.sourceforge.net/index.shtml} for information
#'   about Bowtie and for Rbowtie:
#'   \url{https://www.bioconductor.org/packages/release/bioc/html/Rbowtie.html}.
#'   \url{https://github.com/OestLab/seqpac} for updates on the current package.
#'
#' @param PAC PAC-list object containing an Anno data.frame with sequences as
#'   row names.
#'
#' @param mismatches Integer indicating the maximum number of mismatches allowed
#'   in the alignments. The function currently supports no more than 3
#'   mismatches (botwie max). Default=3. 
#'
#' @param output Character indicating the path to the destination folder
#'   for the temporary files generated by the function. If no output folder is 
#'   defined, files will be stored in a temporary folder and may be removed on 
#'   system restart.
#'
#' @param input_genome List of file paths (character) indicating the full paths to
#'   each fasta reference file used for genome mapping. Note: All reference fasta 
#'   files must have corresponding bowtie indexes. If none exist, you may use
#'   \code{Rbowtie::bowtie_build} to produce them.
#'   
#' @param input_biotype List of file paths (character) indicating the full paths to
#'   each fasta reference file used for biotype mapping. The names in this list 
#'   determines which names will be used in the final annotation. Note: All 
#'   reference fasta files must have bowtie indexes using \code{Rbowtie::bowtie_build}.
#'
#' @param threads Integer indicating the number of parallel processes to be
#'   used. Default=1.  
#'   
#' @param bio_search List of character vectors indicating search terms targeting
#'  feature names in the original reference fasta files. The function will look for
#'  the bio_search terms with \code{\link{grepl}} and annotate accordingly. For
#'  more details on how this works, please see \code{\link{add_reanno}}.
#'  If bio_search is NULL, this function will try to estimate which biotypes that are present
#'  in references used by looking for characters combined with "RNA", e.g "miRNA". 
#'  This assumes the references used have named sequences in such a fashion, and may 
#'  work subpar with some references due to that.
#'   
#' @param save_name logical statement whether to report back full length names of
#' biotype annotations, useful for further annotations such as feature-based annotations. 
#' The default is set to FALSE, as this may create Anno objects of wonky dimensions 
#' with certain reference .fasta files. 
#' 
#' @param hierarchy list of which hierarchy to use for biotype assignment with
#' \code{\link{simplify_reanno}}, where more details can be found on its construction. 
#' If empty, the function will provide a generalized hierarchy based off the biotypes 
#' found in the data following this order: rRNA -> miRNA -> tRNA -> piRNA -> all other.
#' 
#' @param filter_hit If filter_hit is TRUE, sequences without a hit to the reference
#' genome(s) defined in input_genome up until the mismatches defined will be removed.
#' Default is TRUE.
#' 
#' @param override logical whether to write over files in output folder (TRUE),
#' or whether to ask user for console input to confirm overwriting files. Default
#' for this function is TRUE, so be cautious if defining output folder!
#' 
#' @param ... Arguments to be passed on to \code{\link{map_reanno}}, \code{\link{make_reanno}},
#'  \code{\link{add_reanno}}, and \code{\link{simplify_reanno}}.
#'   
#' @return Will return a PAC object with an expanded Anno. 
#'  
#' @examples
#' 
#' #Example for general mapping, for more advanced uses please see
#' #?map_reanno, ?simply_reanno an ?add_reanno
#' 
#' #Ensure we have the mapping references and their bowtie indexes
#' ## genome (here mycoplasma is used due to its small genome size):
#' 
#' mycoplasma_file <- system.file("extdata/mycoplasma_genome",
#'                                "mycoplasma.fa",
#'                                package = "seqpac", mustWork = TRUE)
#' mycoplasma_dir<- gsub("mycoplasma.fa", "", mycoplasma_file)
#' 
#' if(!sum(stringr::str_count(list.files(mycoplasma_dir), ".ebwt")) ==6){
#'   Rbowtie::bowtie_build(mycoplasma_file,
#'                         outdir=mycoplasma_dir,
#'                         prefix="mycoplasma", force=TRUE)
#' }
#' 
#' input_genome <- list(genome=mycoplasma_file)
#' 
#' ## tRNA:
#' trna_file <- system.file("extdata/trna", "tRNA.fa",
#'                          package = "seqpac", mustWork = TRUE)
#' trna_dir <- dirname(trna_file)
#' 
#' if(!sum(stringr::str_count(list.files(trna_dir), ".ebwt")) ==6){
#'   Rbowtie::bowtie_build(trna_file,
#'                         outdir=trna_dir,
#'                         prefix="tRNA", force=TRUE)
#' }
#' ## rRNA:
#' rrna_file <- system.file("extdata/rrna", "rRNA.fa",
#'                          package = "seqpac", mustWork = TRUE)
#' rrna_dir <- dirname(rrna_file)
#' 
#' if(!sum(stringr::str_count(list.files(rrna_dir), ".ebwt")) ==6){
#'   Rbowtie::bowtie_build(rrna_file,
#'                         outdir=rrna_dir,
#'                         prefix="rRNA", force=TRUE)
#' }
#' 
#' input_biotype <- list(trna= trna_file, rrna= rrna_file)
#' 
#' ##  load a PAC-object and remove previous mapping from anno:
#' load(system.file("extdata", "drosophila_sRNA_pac_filt_anno.Rdata",
#'                  package = "seqpac", mustWork = TRUE))
#' anno(pac) <- anno(pac)[,1, drop = FALSE]
#' 
#' pac_anno <- PAC_map(PAC=pac, input_genome=input_genome,
#'                      input_biotype=input_biotype, filter_hit = FALSE) 
#' 
#' @export

#This version of the map provides the user with a "standardised" workflow that makes some assumptions about the
#fasta files. We should check these with some different PACs and different references if we think this is a good 
#function to use moving forward

  
PAC_map <- function(PAC, output=NULL, input_genome,
                    input_biotype=NULL, hierarchy=NULL,
                    bio_search=NULL, mismatches=3, filter_hit=TRUE, 
                    save_name=FALSE, threads=1, override=TRUE, ...){
  
  ## Check S4
  if(isS4(PAC)){
    tp <- "S4"
    PAC <- as(PAC, "list")
  }else{
    tp <- "S3"
  }
  
  #create output folder if this is NULL
  if(is.null(output)){
    output <- paste0(tempdir(),"/seqpac/anno")
    if(!dir.exists(output)){
      dir.create(output, recursive=TRUE)
    }
  }
  
  reanno <- NULL
  
  #genome mapping 
  map_reanno(PAC=PAC, input=input_genome, output=output, mismatches = mismatches, override=override, ...)
  reanno_genome<-make_reanno(PAC=PAC, reanno_path=output, ...)
  PAC <- add_reanno(reanno_genome, type="genome", mismatches = mismatches, merge_pac=PAC)
  
  #filter
  if(filter_hit==TRUE){
    cat(paste0("\nSequences that did not have a hit to reference genome(s) with up to ",mismatches," mismatches will now be removed. 
If you wish to retain these, please rerun the function with filter_hit=FALSE!\n"))
    PAC <- PAC_filter(PAC, anno_target = list("Any_genome", "Hit"))
  }
  
  if(!is.null(input_biotype)){   
  
  #Biotype mapping 
  map_reanno(PAC=PAC, input=input_biotype, output=output, mismatches = mismatches, override=override, ...)
  reanno_biotype<-make_reanno(PAC=PAC, reanno_path=output, ...)
  
  if(is.null(bio_search)){
       
    cat(("\n
    Biotype references have been provided in input_biotype, but no bio_search names for naming have been given. 
    The function will try to find relevant biotypes in references now.
    \n"))
    
    ebt <- as.data.frame(reanno_biotype@Full_anno)
    rownames(ebt)<-ebt[,1]
    ebt <- ebt[,c(colnames(ebt[grep(".*ref_hits", colnames(ebt))]))]
    bio_search_auto <- vector(mode = "list", length = length(input_biotype))
    names(bio_search_auto) <- unique(gsub(".*\\.(.+)\\..*", "\\1",colnames(ebt)))
    
    ebt$seq <- rownames(ebt)
    l_ebt <- reshape2::melt(ebt, id.vars="seq")
    l_ebt[,c("mismatch", "rna")] <- reshape2::colsplit(l_ebt$variable, "\\.",c("mismatch", "rna"))
    l_ebt$rna<-gsub("\\..*","",l_ebt$rna)
    l_ebt2 <- reshape2::dcast(l_ebt, seq + mismatch ~ rna, value.var="value")
    l_ebt2 <- l_ebt2[,-c(1:2)]
    
    for(i in 1:length(bio_search_auto)){
      rna_name <- unique(regmatches(l_ebt2[,i], regexpr("[A-Za-z]*RNA", l_ebt2[,i])))
      #if no hits are found, add name of reference instead
      if(length(rna_name)==0){rna_name <- names(l_ebt2)[i]}
      bio_search_auto[[i]] <- rna_name
      }
    
    nams <- as.character(lapply(bio_search_auto, unique))
    nams <- paste(nams, collapse=", ")
    
    cat(paste0("\nEstimation of biotypes in data have been done (if this was not intended, please rerun script with estimate_biotype=FALSE). Biotypes found in data: \n\n",
          (nams),
          "\n\nIf you believe there are other biotypes that should be available from your references, please add a list manually with 'bio_search' (see ??add_reanno for details)\n"))
    bio_search <- bio_search_auto
  }
  
    op <- add_reanno(reanno_biotype, type="biotype", mismatches = mismatches,
    bio_search = bio_search, bio_perfect = FALSE)
    colnames(op) <- c(colnames(op[1]), paste0(colnames(op[,2:ncol(op)]), "_bio"))
    
    #Add "full" annotation information
    
    if(save_name==TRUE){
      
      level_obj <- as.list(reanno_biotype@Full_anno)
      obj_names <- names(level_obj)
      obj_names <- obj_names[grepl("^mis\\d*$", obj_names)]
      
      if (length(obj_names) == 0) {
        stop("No mis-columns found on reanno object, please check whether mapping finalised correctly")
      }
      
      out_df <- data.frame(row.names = level_obj[[1]][[1]]$seq)
      all_df <- data.frame(row.names = level_obj[[1]][[1]]$seq)
      
      for (i in obj_names) {
        obj <- level_obj[[i]]
        list_names <- names(obj)
        
        for(j in list_names) {
          tib <- obj[[j]]
          if (ncol(tib) < 4) return(NULL)
          out <- tib[, 4, drop = FALSE]
          names(out) <- paste0(i, "_", j)
          out
          out_df <- cbind(out_df, out)
        }
        
        if(ncol(all_df)==0){
          all_df <- out_df
        }
        else{
          all_df <- cbind(all_df, out_df)
        }
      }
      
      colnames(all_df) <- paste0(colnames(all_df), "_FullHit")
      
      if(!is.null(bio_search)){
        op <- cbind(op, all_df)
      }  else{
        op <- all_df
      }
  
  #extract info about tRNA cleavage sites, if tRNAs were found
  if(any(grepl(".*tRNA.*", bio_search))){
    #find tRNA ref
    tRNA_ref <- bio_search[grep(".*tRNA.*", bio_search)]
    tRNA_ref <- input_biotype[names(tRNA_ref)]
    mp <- PAC_mapper(PAC, input=tRNA_ref[[1]], mismatches = mismatches, override = TRUE)
    tc <- tRNA_class(PAC, map=mp)
    if(isS4(tc)){
      tp <- "S4"
      tc <- as(tc, "list")
    }
    tc_df <- tc$Anno[,c("class", "decoder", "acceptor","type")]
    mrg <- merge(x=PAC$Anno, y=tc_df, all.x=TRUE, all.y=FALSE, sort=F, by=0)
    mrg <- mrg[match(rownames(PAC$Anno),mrg$Row.names),]
    rownames(mrg) <- mrg$Row.names
    mrg <- mrg[,!names(mrg) %in% "Row.names"]
    PAC$Anno <- mrg
  }
  
 if(identical(rownames(PAC$Anno), rownames(op))==FALSE){
  warning("Something off in biotype annotation! Suggested route for troubleshooting; 
          go through the reanno workflow manually for biotypes.")
 }
 PAC$Anno <- cbind(PAC$Anno, op)
 
    }else{
      if(identical(rownames(PAC$Anno), rownames(op))==FALSE){
        warning("Something off in biotype annotation! Suggested route for troubleshooting; 
          go through the reanno workflow manually for biotypes.")
      }
      PAC$Anno <- cbind(PAC$Anno, op)
    }
  }
  
  #double check this one
  if(is.null(hierarchy)){
    pat <- (".*_bio")
    g<-grep(pat, colnames(PAC$Anno))
    biotypes_found<-colnames(PAC$Anno)[g]
    hierarchy=list(rRNA="rRNA|rrna", miRNA="miRNA|mirna|mir|miR", tRNA="tRNA|trna", piRNA="piRNA|piR|pirna")
    for(i in 1:length(hierarchy)){
      ifelse(any(grepl(hierarchy[i], biotypes_found)), hierarchy[i]<-hierarchy[i], hierarchy[i]<-NA)
    }
    hierarchy<-hierarchy[!is.na(hierarchy)]
    hier_print <- as.character(names(hierarchy))
    hier_print <- paste(hier_print, collapse=" -> ")
    cat(paste0("\n\nNo hierarchy was provided for biotype annotation. Based on the biotypes annotated in the data, the basic hierarchy of:\n\n",
               (hier_print),"\n\nwill be used. Other biotypes potentially present in this data will be annotated as 'Other'. You may also define a hierarchy manually if you wish to change this, check ?simplify_reanno for more details.\n"))
  }
  
  PAC <- simplify_reanno(input=PAC, hierarchy = hierarchy, mismatches = mismatches, merge_pac = TRUE)
  
  #return PAC object
  stopifnot(PAC_check(PAC))
  if(tp=="S4"){
    return(as.PAC(PAC))
  }else{
    return(PAC)
  }    
}




